# https://docs.travis-ci.com/user/languages/r
language: r
dist: trusty
sudo: false
cache: packages

addons:
  apt:
    packages:
      r-cran-rodbc

r:
  - oldrel # when oldrel = 3.1, there are S3 method problems I can't debug
  - release
  - devel

# compiler:
#   - gcc
#   - clang

matrix:
  allow_failures:
    - r: oldrel
    - os: osx

repos:
  CRAN: https://cloud.r-project.org

warnings_are_errors: true

# seperate lines seems to mean the whole build is repeated each line.
# As of 2013 at least, travis offers ~1.5 cores per process
env:
  - OMP_NUM_THREADS=1 CFLAGS="-O0 -Werror -Wall -Wextra -pedantic -Wno-unused-parameter -Wno-unused-variable" CXXFLAGS="-O0 -Werror -Wall -Wextra -pedantic -Wno-unused-parameter -Wno-unused-variable"
  - OMP_NUM_THREADS=2 CFLAGS="-O3 -march=native" CXXFLAGS="-O3 -march=native"

before_script:
 - ls -R
 - rm .Rinstignore  # do install everything for testing
 - sed -i.old '/[Dd]ata/d' .Rbuildignore # do include data for testing
 - export R_CHECK_CRAN_INCOMING_=FALSE
 - export ICD_SLOW_TESTS=TRUE
 - export _R_CHECK_FORCE_SUGGESTS_=FALSE

after_success:
# environment is copied forward from previous, so slow tests are on. Repeat anyway while not working!
# coverage does re-install the package (it needs to rebuild with debugging/coverage compilation), so there is potential to change .Rinstignore and .Rbuildignore
#  - export ICD_SLOW_TESTS=TRUE
  - ls -R
  - cat ./icd.Rcheck/tests/test-all.Rout
  - Rscript -e 'library(covr); coveralls(quiet = FALSE, line_exclusions = list("inst/include/icd_RcppExports.h", "R/RcppExports.R", "src/RcppExports.cpp", "R/benchmark.R"))'
# TODO automatically show vignettes coverage once regular coverage is working fully
# - Rscript -e 'library(covr); options(warn = -1);  package_coverage(type = "vignette", quiet = FALSE, exclusions = c("inst/include/icd_RcppExports.h", "R/generate_deprecated_data.R", "R/generate_mappings.R", "R/generate_sysdata.R"))'

notifications:
  email:
    on_success: change
    on_failure: change
